apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: {{ .Values.services.dest.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.services.dest.name }}
spec:
  externalName: {{ .Values.services.dest.name }}
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    init_data:
      instance:
        existing_destinations_policy: ignore
        destinations:
          - Name: app1-s4hc-api
            Description: S/4HANA Cloud
            URL: https://sandbox.api.sap.com/s4hanacloud
            Type: HTTP
            ProxyType: Internet
            Authentication: NoAuthentication
            URL.headers.APIKey: {{ .Values.services.dest.APIKey }}
            URL.headers.Application-Interface-Key: {{ .Values.services.dest.ApplicationInterfaceKey }}
